import { Image, Gallery, Footer } from './components';
import { images } from './images';

export const App: React.FC = () => (
  <>
    <div className="container mx-auto mt-24 px-4 md:px-8 lg:px-16">
      <h1 className="font-bold text-4xl my-4">DALL·E Sci-Fi Gallery</h1>
      <p className="mb-8 max-w-[65ch]">
        Welcome to my gallery of science-fiction themed images generated by
        myself using the amazing{' '}
        <a
          className="duration-200 transition-colors text-lime-400 hover:text-lime-600 focus:text-lime-600"
          href="https://openai.com/dall-e-2/"
          target="_blank"
        >
          DALL·E 2
        </a>{' '}
        API. These pictures are a hand-picked selection of my favourite
        generated images.
      </p>
      <Gallery>
        {images.map((image) => (
          <Image id={image.id} caption={image.caption} />
        ))}
      </Gallery>
      <div className="flex justify-center">
        <button
          className="my-8 duration-200 transition-colors text-lime-400 hover:text-lime-600 focus:text-lime-600"
          onClick={() => window.scrollTo(0, 0)}
        >
          Back to Top
        </button>
      </div>
    </div>
    <Footer />
  </>
);
