type ImageTag = 'Realistic' | 'Painting';
export type Filter = ImageTag | 'All';

export interface ImageData {
  id: string;
  caption: string;
  tags: ImageTag[];
}

export const images: ImageData[] = [
  { id: '4d577f', caption: 'Nebula', tags: [] },
  { id: '931c37', caption: 'Space Shuttle', tags: [] },
  { id: 'c87b4d', caption: 'Galaxy', tags: [] },
  { id: 'f1477f', caption: 'Nebula', tags: [] },
  { id: '6e5425', caption: 'Jupiter', tags: [] },
  { id: '0f6e74', caption: 'Satellite', tags: [] },
  { id: '4930ff', caption: 'Black Hole', tags: [] },
  { id: '8a5c72', caption: 'Planet', tags: [] },
  { id: 'f74c50', caption: 'Space Rocket', tags: [] },
  { id: '7e762c', caption: 'Supernovae', tags: [] },
  { id: '06aa35', caption: 'Planet surface', tags: [] },
  { id: '52d746', caption: 'Space shuttle on a moon', tags: [] },
  { id: '98d322', caption: 'Futuristic spaceship', tags: [] },
  { id: '21cdb9', caption: 'Supernovae', tags: [] },
  { id: 'aee219', caption: 'Nebula Cloud', tags: [] },
  { id: '416ea8', caption: 'Satellite', tags: [] },
  { id: 'b7fd62', caption: 'Black Hole', tags: [] },
  { id: '44f5a7', caption: 'Galaxy', tags: [] },
  { id: 'b0c887', caption: 'Futuristic spaceship', tags: [] },
  { id: 'c42e3e', caption: 'Mountainous planet surface', tags: [] },
  { id: 'ef9c83', caption: 'Imperial spaceship', tags: [] },
  { id: 'da0dd0', caption: 'Spaceship', tags: [] },
  { id: '0ce3ec', caption: 'Ancient spaceship', tags: [] },
  { id: '8fe9ad', caption: 'Planets and Nebula', tags: [] },
  { id: 'eb063f', caption: 'Supernovae', tags: [] },
  { id: 'ed0e85', caption: 'Space telescope', tags: [] },
  { id: 'a7bf69', caption: 'Futuristic spaceship', tags: [] },
  { id: '14c127', caption: 'Gateway to a black hole', tags: ['Painting'] },
  { id: '8ef2c0', caption: 'Spiral Galaxy', tags: ['Realistic'] },
  { id: '16d6c7', caption: 'Acretion Disk', tags: ['Realistic'] },
  { id: 'f01e55', caption: 'Nebula', tags: ['Realistic'] },
  { id: 'efc10b', caption: 'Portal', tags: ['Painting'] },
  { id: '7b3add', caption: 'Black Hole', tags: ['Realistic'] },
  { id: '8c0104', caption: 'Nebula', tags: ['Painting'] },
  { id: '5be10c', caption: 'Nebula', tags: ['Realistic'] },
  { id: '77ac1d', caption: 'Southern Ring Nebula', tags: ['Realistic'] },
  { id: '9b7aa0', caption: 'Portal', tags: ['Painting'] },
  { id: '32d714', caption: 'Red Galaxy', tags: ['Realistic'] },
  { id: 'a9ca69', caption: 'Black Hole', tags: ['Painting'] },
  { id: 'cc05a4', caption: 'Carina Nebula', tags: ['Realistic'] },
  { id: 'd63380', caption: 'Pillars of Creation', tags: ['Realistic'] },
  { id: '392772', caption: 'Milky Way Galaxy', tags: ['Realistic'] },
  { id: 'b3e9a1', caption: 'Galaxy', tags: ['Realistic'] },
  { id: '0a8a35', caption: 'Trifid Nebula', tags: ['Realistic'] },
  { id: '2d9157', caption: 'Trifid Nebula', tags: ['Realistic'] },
  { id: '3ab0f6', caption: 'Pillars of Creation', tags: ['Realistic'] },
  { id: 'a673a0', caption: 'Planetary Nebula', tags: ['Realistic'] },
  { id: '3975a3', caption: 'Galaxy', tags: ['Realistic'] },
  { id: '2b0d51', caption: 'Pillars of Creation', tags: ['Realistic'] },
  { id: 'b6ec33', caption: 'Nebula', tags: ['Realistic'] },
  { id: 'dfc555', caption: 'Nebula', tags: ['Realistic'] },
  { id: 'fc11e2', caption: 'Nebula', tags: ['Realistic'] },
  { id: '96c05d', caption: 'Desert planet with moons', tags: ['Realistic'] },
  { id: '050aec', caption: 'Nebula', tags: ['Realistic'] },
  { id: 'dbcb92', caption: 'Nebula', tags: ['Realistic'] },
  { id: '4c034a', caption: 'Nebula', tags: ['Realistic'] },
  { id: '084cb0', caption: 'Galaxy', tags: ['Realistic'] },
  { id: '475cb3', caption: 'Galaxy', tags: ['Realistic'] },
  { id: 'acfdd3', caption: 'Galaxy', tags: ['Realistic'] },
  { id: 'd461e0', caption: 'Pillars of creation', tags: ['Realistic'] },
  { id: 'fcd55f', caption: 'Green sky with nebula', tags: ['Realistic'] },
  { id: '0a8ce5', caption: 'Elliptical Galaxy', tags: ['Realistic'] },
  { id: '2c8a10', caption: 'Nebula', tags: ['Realistic'] },
  { id: '5ceff9', caption: 'Nebula', tags: ['Realistic'] },
  { id: '8bcc38', caption: 'Nebula', tags: ['Realistic'] },
  { id: '8cf4aa', caption: 'Nebula', tags: ['Realistic'] },
];
